"use client"

import * as React from "react"
import { motion, AnimatePresence } from "framer-motion"
import { Sparkles, ListChecks, ChevronDown, ChevronUp, ChevronRight } from "lucide-react"
import { cn } from "@/lib/utils"

interface ArticleSummarizerProps {
  summaryPoints?: string[]
}

export function ArticleSummarizer({ summaryPoints }: ArticleSummarizerProps) {
  const [stage, setStage] = React.useState<"IDLE" | "AD" | "ANALYZING" | "SUMMARY">("IDLE")
  const [isExpanded, setIsExpanded] = React.useState(true)
  const [adTimeLeft, setAdTimeLeft] = React.useState(5)

  const videoRef = React.useRef<HTMLVideoElement>(null)

  const handleSummarize = () => {
    setStage("AD")
    setAdTimeLeft(5)
  }

  // Handle ad countdown
  React.useEffect(() => {
    if (stage === "AD") {
      const timer = setInterval(() => {
        setAdTimeLeft((prev) => {
          if (prev <= 1) {
            clearInterval(timer)
            handleAdComplete()
            return 0
          }
          return prev - 1
        })
      }, 1000)
      return () => clearInterval(timer)
    }
  }, [stage])

  const handleAdComplete = () => {
    setStage("ANALYZING")
    setTimeout(() => {
      setStage("SUMMARY")
      setIsExpanded(true)
    }, 1500)
  }

  if (!summaryPoints || summaryPoints.length === 0) return null

  return (
    <div className="my-12 w-full max-w-3xl mx-auto">
      <motion.div
        layout
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, ease: [0.32, 0.72, 0, 1] }}
        className={cn(
          "relative overflow-hidden rounded-[1rem] transition-all duration-700  ",
          "bg-black/[0.02] dark:bg-white/[0.02] backdrop-blur-3xl border border-black/[0.08] dark:border-white/[0.2] shadow-[0_4px_20px_rgb(0,0,0,0.04)] dark:shadow-[0_2px_20px_rgb(0,0,0,0.1)]",
          stage !== "IDLE" ? "p-6 md:p-8" : "p-4"
        )}
      >
        <AnimatePresence mode="wait">
          {stage === "IDLE" && (
            <motion.button
              key="summarize-button"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0, scale: 0.98 }}
              transition={{ duration: 0.4 }}
              onClick={handleSummarize}
              className="w-full h-full flex items-center justify-between group"
            >
              <div className="flex items-center gap-4 pl-2">
                <div className="relative">
                  <div className="absolute inset-0 bg-primary/30 blur-xl rounded-full scale-[2] animate-pulse" />
                  <Sparkles className="w-6 h-6 text-primary relative z-10" />
                </div>
                <div className="flex flex-col text-left">
                  <span className="text-base font-semibold tracking-tight text-foreground transition-colors">
                    AI Insight Summary
                  </span>
                  <span className="text-xs text-muted-foreground mr-1">Generated by Insight AI</span>
                </div>
              </div>
              <div className="flex items-center gap-3 pr-2">
                <div className="text-[10px] font-bold uppercase tracking-widest text-primary/60 bg-primary/10 px-2 py-1 rounded-full hidden sm:block">
                  Premium
                </div>
                <ChevronDown className="w-5 h-5 text-muted-foreground group-hover:translate-y-0.5 group-hover:text-foreground transition-all" />
              </div>
            </motion.button>
          )}

          {stage === "AD" && (
            <motion.div
              key="ad-state"
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, y: -20, filter: "blur(10px)", scale: 0.95 }}
              transition={{ duration: 0.6, ease: [0.32, 0.72, 0, 1] }}
              className="flex flex-col relative overflow-hidden rounded-2xl"
            >
              {/* Premium Google Ad Container (Apple Style Placeholder) */}
              <div className="relative aspect-video w-full bg-black rounded-xl overflow-hidden group">
                <video
                  ref={videoRef}
                  src="https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"
                  className="w-full h-full object-cover"
                  autoPlay
                  muted
                  playsInline
                />

                {/* Sponsor/Ad Badge */}
                <div className="absolute top-4 left-4 flex items-center gap-2">
                  <span className="backdrop-blur-xl bg-white/10 border border-white/20 text-white text-[10px] font-bold uppercase tracking-widest px-3 py-1.5 rounded-full shadow-lg">
                    Sponsor
                  </span>
                  <div className="w-1.5 h-1.5 rounded-full bg-white/50 animate-pulse" />
                </div>

                {/* Simulated Google Ad Badge */}
                <div className="absolute bottom-4 left-4">
                  <div className="flex items-center gap-1.5 opacity-60">
                    <span className="w-3 h-3 rounded-[2px] bg-white flex items-center justify-center">
                      <span className="w-1.5 h-1.5 bg-blue-500 rounded-full" />
                    </span>
                    <span className="text-[10px] font-medium text-white shadow-sm">Ad by Google</span>
                  </div>
                </div>

                {/* Countdown & Skip */}
                <div className="absolute right-4 bottom-4 flex items-center shadow-lg">
                  {adTimeLeft > 0 ? (
                    <div className="backdrop-blur-xl bg-black/40 border border-white/10 text-white text-xs font-medium px-4 py-2 rounded-full flex items-center gap-2">
                      <motion.svg className="w-4 h-4 -rotate-90" viewBox="0 0 24 24">
                        <circle cx="12" cy="12" r="10" stroke="rgba(255,255,255,0.2)" strokeWidth="2" fill="none" />
                        <motion.circle
                          cx="12" cy="12" r="10"
                          stroke="white"
                          strokeWidth="2"
                          fill="none"
                          strokeDasharray={62.8}
                          initial={{ strokeDashoffset: 62.8 }}
                          animate={{ strokeDashoffset: (adTimeLeft / 5) * 62.8 }}
                          transition={{ duration: 1, ease: "linear" }}
                        />
                      </motion.svg>
                      Ad ends in {adTimeLeft}
                    </div>
                  ) : (
                    <motion.button
                      initial={{ opacity: 0, scale: 0.9 }}
                      animate={{ opacity: 1, scale: 1 }}
                      onClick={handleAdComplete}
                      className="backdrop-blur-xl bg-white text-black text-xs font-bold uppercase tracking-wider px-4 py-2 rounded-full hover:bg-white/90 transition-colors flex items-center gap-1"
                    >
                      Skip Ad
                      <ChevronRight className="w-4 h-4" />
                    </motion.button>
                  )}
                </div>

                {/* Subtle Progress Bar */}
                <div className="absolute bottom-0 left-0 w-full h-[2px] bg-white/20">
                  <motion.div
                    initial={{ width: "0%" }}
                    animate={{ width: `${((5 - adTimeLeft) / 5) * 100}%` }}
                    transition={{ duration: 1, ease: "linear" }}
                    className="h-full bg-primary"
                  />
                </div>
              </div>

              {/* Bottom text whilst ad plays */}
              <div className="absolute inset-x-0 -bottom-10 h-10 flex items-center justify-center pointer-events-none">
                <span className="text-[11px] font-bold text-muted-foreground/60 tracking-widest uppercase">
                  Preparing Summary...
                </span>
              </div>
            </motion.div>
          )}

          {stage === "ANALYZING" && (
            <motion.div
              key="analyzing-state"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0, filter: "blur(10px)" }}
              transition={{ duration: 0.5 }}
              className="flex flex-col items-center justify-center py-12 relative overflow-hidden"
            >
              {/* Volumetric Apple Light */}
              <div className="absolute inset-0 flex items-center justify-center pointer-events-none">
                <motion.div
                  initial={{ scale: 0.8, opacity: 0 }}
                  animate={{
                    scale: [0.8, 1.8, 1.5],
                    opacity: [0, 0.4, 0.2],
                    rotate: 360
                  }}
                  transition={{
                    duration: 3,
                    ease: "easeInOut",
                    rotate: { duration: 10, repeat: Infinity, ease: "linear" }
                  }}

                />
              </div>

              <div className="relative z-10 flex flex-col items-center gap-6">
                <motion.div
                  animate={{
                    rotate: 360,
                  }}
                  transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
                  className="p-3"
                >
                  <Sparkles className="w-8 h-8 text-primary" />
                </motion.div>
                <motion.p
                  animate={{ opacity: [0.5, 1, 0.5] }}
                  transition={{ duration: 2, repeat: Infinity, ease: "easeInOut" }}
                  className="text-sm font-semibold tracking-[0.2em] uppercase text-primary/80"
                >
                  Synthesizing Content...
                </motion.p>
              </div>
            </motion.div>
          )}

          {stage === "SUMMARY" && (
            <motion.div
              key="summary-content"
              initial={{ opacity: 0, scale: 0.98, filter: "blur(10px)" }}
              animate={{ opacity: 1, scale: 1, filter: "blur(0px)" }}
              transition={{ duration: 0.8, ease: [0.32, 0.72, 0, 1] }}
              className="space-y-8"
            >
              <button
                onClick={() => {
                  if (isExpanded) {
                    setIsExpanded(false)
                  } else {
                    setStage("AD")
                    setAdTimeLeft(5)
                  }
                }}
                className="w-full flex items-center justify-between pb-6 group text-left px-1"
              >
                <div className="flex items-center gap-4">
                  <div className="w-10 h-10 bg-black/5 dark:bg-white/10 rounded-[0.8rem] flex items-center justify-center group-hover:scale-105 transition-transform shadow-sm">
                    <ListChecks className="w-5 h-5 text-foreground/70 group-hover:text-foreground transition-colors" />
                  </div>
                  <h3 className="font-semibold text-xl tracking-tight text-foreground/90 group-hover:text-foreground transition-colors">Key Takeaways</h3>
                </div>
                <div className="w-8 h-8 flex items-center justify-center rounded-full bg-black/5 dark:bg-white/5 group-hover:bg-black/10 dark:group-hover:bg-white/10 text-muted-foreground group-hover:text-foreground transition-colors shadow-sm">
                  <motion.div animate={{ rotate: isExpanded ? 0 : 180 }} transition={{ duration: 0.3 }}>
                    <ChevronUp className="w-4 h-4" />
                  </motion.div>
                </div>
              </button>

              <AnimatePresence>
                {isExpanded && (
                  <motion.ul
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    className="flex flex-col rounded-[1.25rem] overflow-hidden bg-black/[0.03] dark:bg-white/[0.03] border  dark:border-white/[0.05]"
                  >
                    {summaryPoints.map((point, index) => (
                      <motion.li
                        key={index}
                        initial={{ opacity: 0, x: -10, filter: "blur(10px)" }}
                        animate={{ opacity: 1, x: 0, filter: "blur(0px)" }}
                        transition={{ delay: index * 0.15, duration: 0.5, ease: [0.32, 0.72, 0, 1] }}
                        className="flex gap-4 items-start p-4 md:p-5 border-b border-black/[0.05] dark:border-white/[0.05] last:border-0 hover:bg-black/[0.02] dark:hover:bg-white/[0.02] transition-colors group"
                      >
                        <div className="flex-shrink-0 w-7 h-7 rounded-[0.4rem] bg-black/5 dark:bg-white/10 flex items-center justify-center text-xs font-bold text-muted-foreground group-hover:text-foreground group-hover:scale-105 transition-all">
                          {index + 1}
                        </div>
                        <p className="text-foreground/90 leading-relaxed text-[15px] font-medium tracking-tight mt-0.5 group-hover:text-foreground transition-colors">
                          {point}
                        </p>
                      </motion.li>
                    ))}
                  </motion.ul>
                )}
              </AnimatePresence>

              <div className="flex items-center gap-3 pt-4">
                <div className="h-[1px] flex-grow bg-gradient-to-r from-transparent via-black/10 dark:via-white/10 to-transparent" />
                <span className="text-[10px] uppercase tracking-[0.25em] text-muted-foreground/60 font-bold whitespace-nowrap bg-black/5 dark:bg-white/5 px-3 py-1 rounded-full border border-black/5 dark:border-white/5">
                  Insight AI Intelligence
                </span>
                <div className="h-[1px] flex-grow bg-gradient-to-r from-transparent via-black/10 dark:via-white/10 to-transparent" />
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </motion.div>
    </div>
  )
}
